#msa
msa-server:
  simple-account:
    port: 10006
  simple-member:
    port: 10007
#eureka
eureka: 
  client:
    service-url:
      defaultZone: http://52.79.120.13:10002/eureka/
  server:
    port: 10002
#Zuul Routing
zuul:
  port: 10003
  routes:
    simpleAcount: #routing Id
      path: /simpleAcount/** #zuul context root
      serviceId: msa-architecture-simple-account #spring application name
      
    simpleMember:
      path: /simpleMember/** #zuul context root
      serviceId: msa-architecture-simple-member #spring application name