spring:
  profile: local
   
msaconfig:
  greeting: "Welcome to local server"

--- 

spring:
  profile: dev
  
msaconfig:
  greeting: "Welcome to dev server"

--- 

spring:
  profile: test
  
msaconfig:
  greeting: "Welcome to test server"

--- 

spring:
  profile: staging
  
msaconfig:
  greeting: "Welcome to staging server"

--- 

spring:
  profile: prod
  
msaconfig:
  greeting: "Welcome to prod server"
