server:
  port: 10001 
spring:
  application:  
    name: msa-architecture-config-server  
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kyungje/MSA_config_server.git